spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eticket
    username: postgres
    password: admin
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false